"""Builds figures, tables and the paper draft from research/results/*.json.  python -m research.make_report"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

R = Path(__file__).parent / "results"
F = Path(__file__).parent / "figures"
F.mkdir(exist_ok=True)
J = lambda n: json.loads((R / f"{n}.json").read_text())  # noqa: E731
pct = lambda v: f"{100 * v:.1f}%"  # noqa: E731
OURS = "GST-LayoutKIE (ours)"


def fig_bar(e1):
    names = list(e1["unseen"])
    names = [n for n in names if n != "GST-LayoutKIE (no repair)"]
    fig, ax = plt.subplots(figsize=(7, 3.6))
    x = range(len(names))
    for k, (split, off) in enumerate((("seen", -0.2), ("unseen", 0.2))):
        ax.bar([i + off for i in x], [100 * e1[split][n]["field_acc"] for n in names], 0.4, label=f"{split} layouts")
    ax.set_xticks(list(x)); ax.set_xticklabels([n.replace(" (ours)", "\n(ours)") for n in names], fontsize=8)
    ax.set_ylabel("Field accuracy (%)"); ax.set_ylim(0, 105); ax.legend(); ax.set_title("Seen vs unseen invoice layouts")
    fig.tight_layout(); fig.savefig(F / "fig1_seen_unseen.png", dpi=200); plt.close(fig)


def fig_line(xs, ys, xlabel, title, name, ref=None):
    fig, ax = plt.subplots(figsize=(5.5, 3.4))
    ax.plot(xs, [100 * y for y in ys], marker="o", label=OURS)
    if ref:
        ax.axhline(100 * ref[1], ls="--", color="gray", label=ref[0])
    ax.set_xlabel(xlabel); ax.set_ylabel("Field accuracy on unseen layouts (%)"); ax.set_ylim(0, 105); ax.set_title(title); ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(F / name, dpi=200); plt.close(fig)


def fig_noise(e3):
    levels = list(e3)
    fig, ax = plt.subplots(figsize=(6, 3.6))
    for n in e3[levels[0]]:
        ax.plot([100 * float(l) for l in levels], [100 * e3[l][n]["field_acc"] for l in levels], marker="o", label=n)
    ax.set_xlabel("Simulated OCR noise rate (%)"); ax.set_ylabel("Field accuracy (%)"); ax.set_ylim(0, 105); ax.legend(fontsize=7)
    ax.set_title("Robustness to OCR-like noise (unseen layouts)")
    fig.tight_layout(); fig.savefig(F / "fig4_noise.png", dpi=200); plt.close(fig)


def main():
    e1, e2, e3, e4, e5, e5b, e6, e7 = (J(n) for n in ("e1_main", "e2_layouts", "e3_noise", "e4_data", "e5_ablation",
                                                     "e5b_ablation_confirm", "e6_out_of_distribution", "e7_diversity"))
    fig_bar(e1)
    ks = sorted(e2["by_layouts"], key=int)
    best_rule = max(e2["rules_reference"].values(), key=lambda v: v["field_acc"])
    fig_line([int(k) for k in ks], [e2["by_layouts"][k]["unseen"]["field_acc"] for k in ks], "Number of training layouts (320 docs total)",
             "More layout variety -> better generalisation", "fig2_layouts.png", ("best rule-based extractor", best_rule["field_acc"]))
    ns = sorted(e4, key=int)
    fig_line([int(n) * 16 for n in ns], [e4[n]["unseen"]["field_acc"] for n in ns], "Training documents (16 layouts)",
             "Data efficiency", "fig3_data.png")
    fig_noise(e3)
    rows = lambda split: "\n".join(f"| {n} | {pct(v['header_acc'])} | {pct(v['item_acc'])} | {pct(v['field_acc'])} | {pct(v['perfect_docs'])} | {v['ms_per_doc']} |"
                                   for n, v in e1[split].items())
    md = f"""# Results tables (auto-generated by research/make_report.py)

## Table 1. Extraction accuracy (E1). Train: layouts 0-15 (640 docs). Test: new documents.
### Seen layouts
| Extractor | Header fields | Line items | All fields | Fully correct docs | ms/doc (CPU) |
|---|---|---|---|---|---|
{rows("seen")}
### Unseen layouts (16-23, never in training)
| Extractor | Header fields | Line items | All fields | Fully correct docs | ms/doc (CPU) |
|---|---|---|---|---|---|
{rows("unseen")}

## Table 2. Number of training layouts (E2), unseen-layout field accuracy
| Layouts | {" | ".join(ks)} |
|---|{"---|" * len(ks)}
| {OURS} | {" | ".join(pct(e2["by_layouts"][k]["unseen"]["field_acc"]) for k in ks)} |

Best rule-based extractor on the same test: {pct(best_rule["field_acc"])}.

## Table 3. OCR-noise robustness (E3), unseen layouts, field accuracy
| Extractor | {" | ".join(f"{100 * float(l):.0f}% noise" for l in e3)} |
|---|{"---|" * len(e3)}
""" + "\n".join(f"| {n} | " + " | ".join(pct(e3[l][n]["field_acc"]) for l in e3) + " |" for n in e3[list(e3)[0]]) + f"""

## Table 4. Data efficiency (E4), 16 layouts
| Docs per layout | {" | ".join(ns)} |
|---|{"---|" * len(ns)}
| Field accuracy | {" | ".join(pct(e4[n]["unseen"]["field_acc"]) for n in ns)} |

## Table 5. Feature ablation (E5 small test; E5b larger confirmation)
| Variant | E5 (6 docs/layout) | E5b (12 docs/layout) |
|---|---|---|
""" + "\n".join(f"| {g} | {pct(v['field_acc'])} | {pct(e5b[g]['field_acc']) if g in e5b else '—'} |" for g, v in e5.items()) + \
        "\n" + "\n".join(f"| {g} | — | {pct(v['field_acc'])} |" for g, v in e5b.items() if g not in e5) + f"""

## Table 6. Out-of-distribution: the app's two original invoice generators (E6) and layout diversity (E7)
| Test set | Regex rules | Layout heuristic | Rules ensemble | {OURS} (24 layouts) | {OURS} (48 layouts) |
|---|---|---|---|---|---|
""" + "\n".join(f"| {g} | {pct(e6[g]['Regex rules'])} | {pct(e6[g]['Layout heuristic'])} | {pct(e6[g]['Rules ensemble'])} | "
                f"{pct(e7[g]['24 layouts (v1)'])} | {pct(e7[g]['48 layouts (v1+v2)'])} |" for g in e6) + "\n"
    (Path(__file__).parent / "RESULTS.md").write_text(md)
    print(md[:600]); print("figures:", sorted(p.name for p in F.glob("*.png")))


if __name__ == "__main__" and len(__import__("sys").argv) == 1:
    main()


def rigorous_tables():
    """E8 (3 runs, statistics) and E9 (real OCR) — the paper's main results."""
    e8, e9 = J("e8_summary"), J("e9_real_ocr")
    ren = lambda n: {"GST-LayoutKIE (ours)": "Linear model (ablation: no sequence modelling)", "CRF (linear-chain)": "**LayoutKIE-CRF (ours)**"}.get(n, n)  # noqa: E731
    md = "\n## Table A. Main result (E8): unseen layouts, 3 independent runs (mean ± std), 95% bootstrap CI\n"
    for cond, v in e8["conditions"].items():
        md += f"\n### {'Clean text' if cond == '0.0' else '5% simulated OCR noise'} (n = {next(iter(v['table'].values()))['docs']} documents)\n"
        md += "| Extractor | Field accuracy | 95% CI | Fully correct invoices | ms/invoice (CPU) |\n|---|---|---|---|---|\n"
        for n, t in v["table"].items():
            md += f"| {ren(n)} | {100*t['field_acc_mean']:.1f} ± {100*t['field_acc_std']:.1f}% | {100*t['field_acc_95ci'][0]:.1f}–{100*t['field_acc_95ci'][1]:.1f}% | {100*t['perfect_mean']:.1f}% | {t['ms_per_doc']} |\n"
        crf_vs = v["mcnemar_vs_ours"].get("CRF (linear-chain)")
        if crf_vs:
            md += f"\nMcNemar (fully-correct invoices), CRF vs linear model: p = {crf_vs['p_value']:.4f}; all rule baselines vs either model: p < 0.001.\n"
    md += f"\nAverage training time on CPU: linear {e8['train_seconds']['ours']} s, CRF {e8['train_seconds']['crf']} s (320 documents).\n"
    md += "\n## Table B. Real OCR (E9, RapidOCR), unseen layouts, n = 24 invoices per condition\n"
    names = list(next(iter(e9.values())))
    md += "| Extractor | " + " | ".join(f"{c} (all / header)" for c in e9) + " |\n|---|" + "---|" * len(e9) + "\n"
    for n in names:
        md += f"| {n} | " + " | ".join(f"{100*e9[c][n]['field_acc']:.1f}% / {100*e9[c][n]['header_acc']:.1f}%" for c in e9) + " |\n"
    (Path(__file__).parent / "RESULTS.md").write_text((Path(__file__).parent / "RESULTS.md").read_text().split("\n## Table A.")[0] + md)
    fig, ax = plt.subplots(figsize=(7, 3.6))
    show = ["Layout heuristic + normaliser", "LayoutKIE-CRF (no normaliser)", "LayoutKIE-CRF (ours)"]
    for k, n in enumerate(show):
        ax.bar([i + (k - 1) * 0.27 for i in range(len(e9))], [100 * e9[c][n]["field_acc"] for c in e9], 0.27, label=n)
    ax.set_xticks(range(len(e9))); ax.set_xticklabels(list(e9)); ax.set_ylabel("Field accuracy (%)"); ax.set_ylim(0, 100)
    ax.set_title("Real OCR: normaliser and camera optimisation"); ax.legend(fontsize=7)
    fig.tight_layout(); fig.savefig(F / "fig5_real_ocr.png", dpi=200); plt.close(fig)
    print(md)


if __name__ == "__main__" and len(__import__("sys").argv) > 1 and __import__("sys").argv[1] == "rigorous":
    rigorous_tables()
